# app-config.yaml
theme:
  # Các theme khả dụng
  available:
    - light
    - dark
    - system
  # Theme đang sử dụng
  current: system

color_scheme:
  # Các màu khả dụng
  available:
    - blue
    - green
    - dark-blue
  # Màu đang sử dụng
  current: dark-blue